rootProject.name="micronaut-demo"

//includeBuild("../micronaut-core"){
//    dependencySubstitution{
//        substitute(module("io.micronaut:micronaut-aop")).using(project(":aop"))
//        substitute(module("io.micronaut:micronaut-buffer-netty")).using(project(":buffer-netty"))
//        substitute(module("io.micronaut:micronaut-context")).using(project(":context"))
//        substitute(module("io.micronaut:micronaut-context-propagation")).using(project(":context-propagation"))
//        substitute(module("io.micronaut:micronaut-core")).using(project(":core"))
//        substitute(module("io.micronaut:micronaut-core-bom")).using(project(":core-bom"))
//        substitute(module("io.micronaut:micronaut-discovery-core")).using(project(":discovery-core"))
//        substitute(module("io.micronaut:micronaut-function")).using(project(":function"))
//        substitute(module("io.micronaut:micronaut-function-client")).using(project(":function-client"))
//        substitute(module("io.micronaut:micronaut-function-web")).using(project(":function-web"))
//        substitute(module("io.micronaut:micronaut-graal")).using(project(":graal"))
//        substitute(module("io.micronaut:micronaut-http")).using(project(":http"))
//        substitute(module("io.micronaut:micronaut-http-client")).using(project(":http-client"))
//        substitute(module("io.micronaut:micronaut-http-client-core")).using(project(":http-client-core"))
//        substitute(module("io.micronaut:micronaut-http-client-jdk")).using(project(":http-client-jdk"))
//        substitute(module("io.micronaut:micronaut-http-client-tck")).using(project(":http-client-tck"))
//        substitute(module("io.micronaut:micronaut-http-netty")).using(project(":http-netty"))
//        substitute(module("io.micronaut:micronaut-http-server")).using(project(":http-server"))
//        substitute(module("io.micronaut:micronaut-http-server-netty")).using(project(":http-server-netty"))
//        substitute(module("io.micronaut:micronaut-http-server-tck")).using(project(":http-server-tck"))
//        substitute(module("io.micronaut:micronaut-http-tck")).using(project(":http-tck"))
//        substitute(module("io.micronaut:micronaut-http-validation")).using(project(":http-validation"))
//        substitute(module("io.micronaut:micronaut-inject")).using(project(":inject"))
//        substitute(module("io.micronaut:micronaut-inject-groovy")).using(project(":inject-groovy"))
//        substitute(module("io.micronaut:micronaut-inject-groovy-test")).using(project(":inject-groovy-test"))
//        substitute(module("io.micronaut:micronaut-inject-java")).using(project(":inject-java"))
//        substitute(module("io.micronaut:micronaut-inject-java-helper")).using(project(":inject-java-helper"))
//        substitute(module("io.micronaut:micronaut-inject-java-test")).using(project(":inject-java-test"))
//        substitute(module("io.micronaut:micronaut-inject-kotlin")).using(project(":inject-kotlin"))
//        substitute(module("io.micronaut:micronaut-inject-kotlin-test")).using(project(":inject-kotlin-test"))
//        substitute(module("io.micronaut:micronaut-inject-test-utils")).using(project(":inject-test-utils"))
//        substitute(module("io.micronaut:micronaut-jackson-core")).using(project(":jackson-core"))
//        substitute(module("io.micronaut:micronaut-jackson-databind")).using(project(":jackson-databind"))
//        substitute(module("io.micronaut:micronaut-json-core")).using(project(":json-core"))
//        substitute(module("io.micronaut:micronaut-management")).using(project(":management"))
//        substitute(module("io.micronaut:micronaut-messaging")).using(project(":messaging"))
//        substitute(module("io.micronaut:micronaut-retry")).using(project(":retry"))
//        substitute(module("io.micronaut:micronaut-router")).using(project(":router"))
//        substitute(module("io.micronaut:micronaut-runtime")).using(project(":runtime"))
//        substitute(module("io.micronaut:micronaut-runtime-osx")).using(project(":runtime-osx"))
//        substitute(module("io.micronaut:micronaut-websocket")).using(project(":websocket"))
//    }
//}